### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by ZahraAnam** [stefan-m-lenz/BoltzmannMachines.jl#1]
Dear,
I was searching for RBM implementation that can be generalised well and your work seems an answer but I have pointcloud data so I must need to use GPU,
Can you help me incorporate GPU into the code.
Its my first experience to Julia, I started finding basics to use it.

**Comment by stefan-m-lenz** [comment]
Dear Zahra,
thank you very much for your interest!
Getting code to run on GPU, and especially writing code that runs *effectively* on GPU, is a very challenging task. It is currently not planned to support GPUs in this package and it probably would need a lot of thinking to change or extend the design to enable an efficient GPU support.
I would recommend that you at first check whether you can achieve an acceptable performance in your use case without a GPU, using your actual data and some code, before you go further in the direction of optimisation.
Good luck with your project!
Stefan

**Comment by ZahraAnam** [comment]
Its v slow even with the data you have randomly initialized. Regards Sent from my Huawei phone-------- Original message --------From: Stefan Lenz <notifications@github.com>Date: Wed., Dec. 4, 2019, 3:34 p.m.To: "stefan-m-lenz/BoltzmannMachines.jl" <BoltzmannMachines.jl@noreply.github.com>Cc: ZahraAnam <zahraa.anam@gmail.com>, Author <author@noreply.github.com>Subject: Re: [stefan-m-lenz/BoltzmannMachines.jl] GPU (#1)Dear Zahra,
thank you very much for your interest!
Getting code to run on GPU, and especially writing code that runs effectively on GPU, is a very challenging task. It is currently not planned to support GPUs in this package and it probably would need a lot of thinking to change or extend the design to enable an efficient GPU support.
I would recommend that you at first check whether you can achieve an acceptable performance in your use case without a GPU, using your actual data and some code, before you go further in the direction of optimisation.
Good luck with your project!
Stefan
